"""
Tech term vocabulary for matching against job descriptions.

Sources:
  * Stack Overflow 2025 Developer Survey response options (survey.stackoverflow.co/2025/technology),
    data licensed ODbL. These are the exact option names developers were asked about, which makes
    them a decent market-derived vocabulary rather than a resume-writing list.
  * DATA_ML_SUPPLEMENT is my own addition: the 2025 survey dropped its "other frameworks and
    libraries" section, so pandas, PyTorch, Spark, Airflow, dbt, etc. are not in it.

Each entry is (canonical_name, [surface forms to match]). Surface forms are lowercase.
Matching should use word boundaries; short forms like "r", "c", "go" are deliberately
given only unambiguous surface forms and will undercount.
"""

LANGUAGES = [
    ("JavaScript", ["javascript"]),
    ("HTML/CSS", ["html", "css", "html/css"]),
    ("SQL", ["sql"]),
    ("Python", ["python"]),
    ("Bash/Shell", ["bash", "shell scripting", "shell"]),
    ("TypeScript", ["typescript"]),
    ("Java", ["java"]),                       # boundary-matched so it won't hit "javascript"
    ("C#", ["c#", "csharp"]),
    ("C++", ["c++", "cpp"]),
    ("PowerShell", ["powershell"]),
    ("C", []),                                # unmatchable by substring; leave empty
    ("PHP", ["php"]),
    ("Go", ["golang", "go (golang)", "go/golang"]),
    ("Rust", ["rust"]),
    ("Kotlin", ["kotlin"]),
    ("Lua", ["lua"]),
    ("Assembly", ["assembly language"]),
    ("Ruby", ["ruby"]),
    ("Dart", ["dart/flutter", "flutter/dart", "dart language"]),
    ("Swift", ["swiftui", "swift/ios", "ios/swift", "swift and", "and swift", "swift,", "objective-c/swift"]),
    ("R", ["r language", "r programming", "r/python", "python/r"]),
    ("Groovy", ["groovy"]),
    ("Visual Basic (.NET)", ["vb.net", "visual basic"]),
    ("VBA", ["vba"]),
    ("MATLAB", ["matlab"]),
    ("Perl", ["perl"]),
    ("GDScript", ["gdscript"]),
    ("Elixir", ["elixir"]),
    ("Scala", ["scala"]),
    ("Delphi", ["delphi/pascal", "embarcadero delphi"]),
    ("Lisp", ["common lisp", "clojure", "clojurescript"]),
    ("MicroPython", ["micropython"]),
    ("Zig", ["zig language", "ziglang"]),
    ("Erlang", ["erlang"]),
    ("Fortran", ["fortran"]),
    ("Ada", ["ada language", "ada/spark"]),
    ("F#", ["f#"]),
    ("OCaml", ["ocaml"]),
    ("Gleam", ["gleam language"]),
    ("Prolog", ["prolog"]),
    ("COBOL", ["cobol"]),
    ("Mojo", ["mojo language"]),
    ("Haskell", ["haskell"]),
    ("Julia", ["julia"]),
    ("Objective-C", ["objective-c", "objective c"]),
]

DATABASES = [
    ("PostgreSQL", ["postgresql", "postgres"]),
    ("MySQL", ["mysql"]),
    ("SQLite", ["sqlite"]),
    ("Microsoft SQL Server", ["sql server", "mssql", "t-sql"]),
    ("Redis", ["redis"]),
    ("MongoDB", ["mongodb", "mongo"]),
    ("MariaDB", ["mariadb"]),
    ("Elasticsearch", ["elasticsearch", "elastic search", "opensearch"]),
    ("Oracle", ["oracle database", "oracle db", "oracle sql"]),
    ("DynamoDB", ["dynamodb"]),
    ("BigQuery", ["bigquery"]),
    ("Supabase", ["supabase"]),
    ("Cloud Firestore", ["firestore"]),
    ("H2", ["h2 database"]),
    ("Firebase Realtime Database", ["firebase realtime"]),
    ("Microsoft Access", ["microsoft access", "ms access"]),
    ("Cosmos DB", ["cosmos db", "cosmosdb"]),
    ("Snowflake", ["snowflake"]),
    ("InfluxDB", ["influxdb"]),
    ("Databricks SQL", ["databricks"]),
    ("DuckDB", ["duckdb"]),
    ("Cassandra", ["cassandra"]),
    ("Neo4j", ["neo4j"]),
    ("Valkey", ["valkey"]),
    ("ClickHouse", ["clickhouse"]),
    ("IBM Db2", ["db2"]),
    ("Amazon Redshift", ["redshift"]),
    ("CockroachDB", ["cockroachdb"]),
    ("PocketBase", ["pocketbase"]),
    ("Datomic", ["datomic"]),
    ("CouchDB", ["couchdb"]),
    ("Couchbase", ["couchbase"]),
    ("TimescaleDB", ["timescaledb"]),
]

CLOUD_INFRA = [
    ("Docker", ["docker"]),
    ("npm", ["npm"]),
    ("AWS", ["aws", "amazon web services"]),
    ("pip", []),
    ("Kubernetes", ["kubernetes", "k8s"]),
    ("Microsoft Azure", ["azure"]),
    ("Homebrew", []),
    ("Vite", ["vite"]),
    ("Google Cloud", ["google cloud", "gcp"]),
    ("Make", ["makefile", "gnu make"]),
    ("Yarn", ["npm/yarn", "yarn/npm", "yarn workspaces"]),
    ("Cloudflare", ["cloudflare"]),
    ("NuGet", ["nuget"]),
    ("APT", []),
    ("Webpack", ["webpack"]),
    ("Terraform", ["terraform"]),
    ("Maven", ["maven"]),
    ("Cargo", ["cargo.toml"]),
    ("Gradle", ["gradle"]),
    ("pnpm", ["pnpm"]),
    ("Firebase", ["firebase"]),
    ("Prometheus", ["prometheus"]),
    ("Ansible", ["ansible"]),
    ("Podman", ["podman"]),
    ("Chocolatey", []),
    ("Composer", ["php composer", "composer.json"]),
    ("MSBuild", ["msbuild"]),
    ("DigitalOcean", ["digitalocean", "digital ocean"]),
    ("Vercel", ["vercel"]),
    ("Poetry", ["poetry.lock", "pyproject"]),
    ("Datadog", ["datadog"]),
    ("Pacman", []),
    ("Netlify", ["netlify"]),
    ("Bun", ["bun.js", "bun runtime", "bun.sh"]),
    ("Heroku", ["heroku"]),
    ("Ninja", ["ninja build"]),
    ("Splunk", ["splunk"]),
    ("New Relic", ["new relic", "newrelic"]),
    ("Railway", []),
    ("IBM Cloud", ["ibm cloud"]),
    ("Yandex Cloud", ["yandex cloud"]),
]

WEB_FRAMEWORKS = [
    ("Node.js", ["node.js", "nodejs", "node js"]),
    ("React", ["react", "react.js", "reactjs"]),
    ("jQuery", ["jquery"]),
    ("Next.js", ["next.js", "nextjs"]),
    ("Express", ["express.js", "expressjs"]),
    ("ASP.NET Core", ["asp.net core"]),
    ("Angular", ["angular"]),
    ("Vue.js", ["vue", "vue.js", "vuejs"]),
    ("FastAPI", ["fastapi"]),
    ("Spring Boot", ["spring boot", "spring framework", "spring mvc", "spring cloud", "java/spring", "spring/java"]),
    ("Flask", ["flask"]),
    ("ASP.NET", ["asp.net"]),
    ("WordPress", ["wordpress"]),
    ("Django", ["django"]),
    ("Laravel", ["laravel"]),
    ("AngularJS", ["angularjs"]),
    ("Svelte", ["svelte"]),
    ("Blazor", ["blazor"]),
    ("NestJS", ["nestjs", "nest.js"]),
    ("Ruby on Rails", ["ruby on rails", "rails"]),
    ("Astro", ["astro.build", "astro framework"]),
    ("Deno", ["deno"]),
    ("Symfony", ["symfony"]),
    ("Nuxt.js", ["nuxt", "nuxt.js"]),
    ("Fastify", ["fastify"]),
    ("Axum", ["axum"]),
    ("Phoenix", ["phoenix framework", "elixir/phoenix", "phoenix liveview"]),
    ("Drupal", ["drupal"]),
    ("htmx", ["htmx"]),
    ("SolidJS", ["solidjs", "solid.js"]),
    ("Flutter", ["flutter"]),
    ("Quarkus", ["quarkus"]),
    ("Hugo", []),
    ("Tailwind CSS", ["tailwind"]),
    ("shadcn/ui", ["shadcn"]),
]

AI_RISING = [
    ("Google Gemini", []),   # counted under LLM_MODELS
    ("Large language model", ["large language model", "llm", "llms"]),
    (".NET 8+", [".net 8", ".net core", ".net"]),
    ("Ollama", ["ollama"]),
    ("RAG", ["retrieval-augmented generation", "retrieval augmented generation", "(rag)", "rag pipeline", "rag pipelines", "rag system", "rag systems", "rag-based", "rag architecture", "rag applications"]),
    ("Pydantic", ["pydantic"]),
    ("uv", ["uv package"]),
    ("Amazon Bedrock", ["bedrock"]),
    ("Polars", ["polars"]),
    ("LangGraph", ["langgraph"]),
    ("Microsoft Fabric", ["microsoft fabric"]),
    ("SwiftData", ["swiftdata"]),
    ("Ultralytics", ["ultralytics", "yolo"]),
]

LLM_MODELS = [
    ("OpenAI GPT", ["openai", "gpt-4", "gpt-5", "chatgpt"]),
    ("Claude", ["claude", "anthropic"]),
    ("Gemini", ["gemini"]),
    ("DeepSeek", ["deepseek"]),
    ("Meta Llama", ["meta llama", "llama 3", "llama-3", "llama 4", "llama-4", "llama.cpp", "llama models"]),
    ("Grok", ["x grok", "xai grok", "grok api", "grok models"]),
    ("Mistral", ["mistral"]),
    ("Perplexity", ["perplexity"]),
    ("Qwen", ["qwen"]),
    ("Phi", ["phi-4", "phi-3"]),
    ("Cohere", ["cohere"]),
]

COLLAB_TOOLS = [
    ("GitHub", ["github"]),
    ("Jira", ["jira"]),
    ("GitLab", ["gitlab"]),
    ("Confluence", ["confluence"]),
    ("Azure DevOps", ["azure devops"]),
    ("Notion", ["notion.so", "notion workspace"]),
    ("Miro", ["miro"]),
    ("Trello", ["trello"]),
    ("Google Colab", ["colab"]),
    ("Lucidchart", ["lucidchart"]),
    ("Asana", ["asana"]),
    ("ClickUp", ["clickup"]),
    ("Linear", []),
    ("Monday.com", ["monday.com"]),
    ("Airtable", ["airtable"]),
    ("Bitbucket", ["bitbucket"]),
    ("Slack", ["slack api", "slack integration", "slack bot", "slack app"]),
    ("DevOps", ["devops"]),  # david added
    ("Code as Infrastructure", ["code as infrastructure"]),  # david added
]

# Not in the 2025 survey; added because they're the core of data / ML job postings.
DATA_ML_SUPPLEMENT = [
    ("pandas", ["pandas"]),
    ("NumPy", ["numpy"]),
    ("scikit-learn", ["scikit-learn", "sklearn", "scikit learn"]),
    ("PyTorch", ["pytorch", "torch"]),
    ("TensorFlow", ["tensorflow"]),
    ("Keras", ["keras"]),
    ("JAX", ["jax"]),
    ("Hugging Face", ["hugging face", "huggingface", "transformers"]),
    ("LangChain", ["langchain"]),
    ("LlamaIndex", ["llamaindex", "llama index"]),
    ("Vector database", ["vector database", "vector databases", "vector db", "vector store", "vector search", "pinecone", "weaviate", "pgvector", "milvus", "qdrant", "chromadb", "chroma db"]),
    ("Apache Spark", ["spark", "pyspark"]),
    ("Apache Kafka", ["kafka"]),
    ("Apache Airflow", ["airflow"]),
    ("dbt", ["dbt"]),
    ("Apache Flink", ["flink"]),
    ("Hadoop", ["hadoop"]),
    ("Dagster", ["dagster"]),
    ("Prefect", ["prefect"]),
    ("Fivetran", ["fivetran"]),
    ("Looker", ["looker"]),
    ("Tableau", ["tableau"]),
    ("Power BI", ["power bi", "powerbi"]),
    ("Jupyter", ["jupyter"]),
    ("MLflow", ["mlflow"]),
    ("Kubeflow", ["kubeflow"]),
    ("SageMaker", ["sagemaker"]),
    ("Vertex AI", ["vertex ai"]),
    ("Ray", ["ray.io", "ray cluster", "anyscale"]),
    ("Streamlit", ["streamlit"]),
    ("GraphQL", ["graphql"]),
    ("gRPC", ["grpc"]),
    ("REST", ["rest api", "restful"]),
    ("CI/CD", ["ci/cd", "continuous integration", "continuous delivery", "continuous deployment"]),
    ("GitHub Actions", ["github actions"]),
    ("Jenkins", ["jenkins"]),
    ("ArgoCD", ["argocd", "argo cd"]),
    ("Helm", ["helm"]),
    ("Pulumi", ["pulumi"]),
    ("Grafana", ["grafana"]),
    ("OpenTelemetry", ["opentelemetry"]),
    ("Linux", ["linux"]),
    ("Microservices", ["microservices", "microservice"]),
    ("Distributed systems", ["distributed systems"]),
    ("Machine learning", ["machine learning", "ml models", "deep learning"]),
    ("NLP", ["nlp", "natural language processing"]),
    ("Computer vision", ["computer vision"]),
    ("Agents", ["ai agents", "agentic", "agent frameworks", "mcp"]),
    ("Evals", ["evals", "evaluation framework", "llm evaluation"]),
    ("Prompt engineering", ["prompt engineering"]),
    ("Fine-tuning", ["fine-tuning", "fine tuning", "finetuning"]),
]

# Practices, domains, and concepts.
GENERAL_CONCEPTS = [
    ("DevOps", ["devops", "dev ops"]),
    ("SRE", ["sre", "site reliability"]),
    ("Infrastructure as code", ["infrastructure as code", "infrastructure-as-code", "iac"]),
    ("Cloud", ["cloud platforms", "cloud infrastructure", "cloud services", "cloud-native", "cloud native", "cloud deployments", "public cloud"]),
    ("Monitoring / observability", ["monitoring", "observability", "alerting", "logging"]),
    ("Deployment", ["deployment", "deployments", "deploy", "release management"]),
    ("Automation", ["automation", "automate", "automated"]),
    ("Backend", ["backend", "back-end", "back end", "server-side", "server side"]),
    ("Frontend", ["frontend", "front-end", "front end", "client-side", "user interface", "ui/ux"]),
    ("Full stack", ["full stack", "full-stack", "fullstack"]),
    ("API", ["api", "apis", "api design", "web services"]),
    ("Data pipelines", ["data pipeline", "data pipelines", "etl", "elt", "data ingestion"]),
    ("Data warehouse", ["data warehouse", "data warehousing", "data lake", "lakehouse"]),
    ("Data modeling", ["data modeling", "data modelling", "schema design", "dimensional modeling"]),
    ("Analytics", ["analytics", "dashboards", "dashboard", "business intelligence", "reporting"]),
    ("Statistics", ["statistics", "statistical", "a/b testing", "experimentation"]),
    ("AI", ["ai", "artificial intelligence", "generative ai", "genai", "gen ai", "ai-powered", "ai/ml", "ml/ai"]),
    ("Software development", ["software development", "software engineering", "software design", "programming", "coding", "writing code"]),
    ("Version control", ["version control", "git", "source control", "pull requests", "code review", "code reviews"]),
    ("Testing", ["unit tests", "unit testing", "integration tests", "test automation", "automated testing", "tdd", "test-driven"]),
    ("Agile", ["agile", "scrum", "kanban", "sprints", "sprint"]),
    ("System design", ["system design", "systems design", "architecture", "architectural", "scalability", "scalable", "high availability", "fault-tolerant", "fault tolerant"]),
    ("Security", ["security", "authentication", "authorization", "encryption", "vulnerabilities", "appsec", "devsecops"]),
    ("Networking", ["networking", "tcp/ip", "dns", "load balancing", "load balancers"]),
    ("Containers", ["containers", "containerization", "containerized"]),
    ("Serverless", ["serverless", "lambda", "cloud functions"]),
    ("Performance", ["performance tuning", "performance optimization", "latency", "throughput"]),
    ("Data structures & algorithms", ["data structures", "algorithms"]),
    ("Concurrency", ["concurrency", "multithreading", "multi-threaded", "asynchronous", "async"]),
    ("Embedded", ["embedded systems", "firmware", "rtos", "microcontroller", "microcontrollers"]),
    ("Mobile", ["mobile development", "mobile apps", "ios development", "android development"]),
    ("Model training", ["model training", "training models", "fine-tune", "inference", "model deployment", "mlops"]),
]
 
# Signs that a post is an AI-training / annotation gig or an hourly freelance
# engagement rather than a job. Count these to flag, not to score technical depth.
GIG_SIGNALS = [
    ("AI training gig", ["ai-generated outputs", "ai-generated content", "ai-generated responses", "evaluate ai responses",
                         "ai lab", "ai labs", "ai trainer", "ai training", "rlhf", "human feedback", "training data",
                         "data annotation", "annotation", "annotate", "annotators", "labeling", "labelling",
                         "quality rater", "rater", "raters", "expert network", "domain expert", "domain experts",
                         "review and refine", "grade responses", "rank responses", "per task", "per hour of work"]),
    ("Freelance / hourly", ["freelance", "freelancer", "freelancers", "hrs/week", "hours per week", "hours/week", "hourly rate",
                            "per hour", "contractor", "1099", "independent contractor", "part-time", "part time"]),
    ("Not a real opening", ["not traditional job openings", "not a traditional job", "talent community", "talent pool",
                            "future opportunities", "general application", "evergreen", "pipeline for future"]),
]
 
CATEGORIES = {
    "language": LANGUAGES,
    "database": DATABASES,
    "cloud_infra": CLOUD_INFRA,
    "web_framework": WEB_FRAMEWORKS,
    "ai_rising": AI_RISING,
    "llm_model": LLM_MODELS,
    "collab_tool": COLLAB_TOOLS,
    "data_ml": DATA_ML_SUPPLEMENT,
    "concept": GENERAL_CONCEPTS,
    "gig_signal": GIG_SIGNALS,
}
 
 
def surface_forms():
    """Yield (surface_form, canonical_name, category) for every matchable form."""
    for category, entries in CATEGORIES.items():
        for canonical, forms in entries:
            for form in forms:
                yield form, canonical, category
 